name: liveview_pwa
services:
  pg:
    image: postgres:17
    container_name: pg17

    environment:
      # PostgreSQL environment variables are in the form POSTGRES_*
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: elec_prod

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    # volumes:
    #   - pgdata:/var/lib/postgresql/data

    ports:
      - "3001:5432"

    tmpfs:
      - /var/lib/postgresql/data
      - /tmp

    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10

  web:
    container_name: web
    depends_on:
      pg:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - sql3:/app/db
    user: nobody
    env_file:
      - .env.docker
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081

volumes:
  sql3:
    name: sql3
  # pgdata:
  #   name: pgdata
