services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - db:/app/db
    user: nobody
    env_file:
      - .env

volumes:
  db:
    name: db
