# fly.toml app configuration file generated for liveview-pwa on 2025-05-25T18:27:19-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'liveview-pwa'
primary_region = 'bog'
kill_signal = 'SIGTERM'

[build]

[deploy]
release_command = '/app/bin/migrate'

[env]
DATABASE_PATH = '/data/db/main.sqlite3'
ECTO_IPV6 = 'true'
ERL_AFLAGS = '-proto_dist inet6_tcp'
MIX_ENV = 'prod'
PHX_HOST = 'liveview-pwa.fly.dev'
PORT = '8080'

# [processes]
# app = 'root'

[[mounts]]
source = 'db'
destination = '/data'
auto_extend_size_threshold = 80
auto_extend_size_increment = '1GB'
auto_extend_size_limit = '10GB'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
