# fly.toml app configuration file generated for liveview-pwa on 2025-05-21T21:44:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'liveview-pwa'
primary_region = 'bog'
kill_signal = 'SIGTERM'

[build]

[deploy]
release_command = '/app/bin/migrate'

[env]
DATABASE_PATH = '/mnt/db/app/main.db'
DATABASE_URL = 'postgres://postgres:ndmLhXhl5cTXqyY@liveview-pwa-db.flycast:5432/liveview_pwa_prod'
MIX_ENV = 'prod'
PHX_HOST = 'liveview-pwa.fly.dev'
PORT = '8080'

[[mounts]]
source = 'db'
destination = '/mnt'
auto_extend_size_threshold = 80
auto_extend_size_increment = '1GB'
auto_extend_size_limit = '10GB'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
