packages:
  - assets
  - deps/phoenix
  - deps/phoenix_html
  - deps/phoenix_live_view

ignoredBuiltDependencies:
  - pngquant-bin
  - tree-sitter-typescript

onlyBuiltDependencies:
  - '@mongodb-js/zstd'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - tree-sitter
  - tree-sitter-javascript
  - unrs-resolver
